# Generated by Django 3.2.7 on 2021-11-01 02:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookmanager", "0002_book_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("book", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bookmanager.book")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(fields=("user", "book"), name="unique_reservation"),
        ),
    ]
