# Generated by Django 3.2.7 on 2021-10-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="line_uid",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name="line uid"),
        ),
    ]
